# Uncomment this line to define a global platform for your project
platform :ios, '17.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  # Explicitly add Reachability pod with correct name
  pod 'ReachabilitySwift', '~> 5.0', :modular_headers => true

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    
    # Fix for geolocator_apple 'Flutter/Flutter.h' file not found error
    target.build_configurations.each do |config|
      # Enforce iOS 17.0 deployment target for all pods
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '17.0'
      
      # Make sure all pods use the same iOS version
      config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
      
      # Fix module import issues
      config.build_settings['SWIFT_VERSION'] = '5.0'
      config.build_settings['DEFINES_MODULE'] = 'YES'
      
      # Fix for Reachability module not found
      config.build_settings['SWIFT_INCLUDE_PATHS'] = '$(PODS_ROOT)/ReachabilitySwift'
      config.build_settings['HEADER_SEARCH_PATHS'] = '$(inherited) ${PODS_ROOT}/ReachabilitySwift'
      
      config.build_settings['FRAMEWORK_SEARCH_PATHS'] ||= []
      config.build_settings['FRAMEWORK_SEARCH_PATHS'] << "${PODS_ROOT}/../Flutter"
      config.build_settings['FRAMEWORK_SEARCH_PATHS'] << "${PODS_XCFRAMEWORKS_BUILD_DIR}/Flutter"
      config.build_settings['FRAMEWORK_SEARCH_PATHS'] << "${BUILT_PRODUCTS_DIR}"
      
      config.build_settings['HEADER_SEARCH_PATHS'] ||= []
      config.build_settings['HEADER_SEARCH_PATHS'] << "${PODS_ROOT}/Headers/Public/Flutter"
      config.build_settings['HEADER_SEARCH_PATHS'] << "${PODS_ROOT}/../Flutter"
      config.build_settings['HEADER_SEARCH_PATHS'] << "${BUILT_PRODUCTS_DIR}/Flutter.framework/Headers"
      
      # Ensure proper import paths for geolocator_apple
      if target.name == 'geolocator_apple'
        config.build_settings['HEADER_SEARCH_PATHS'] << "${PODS_ROOT}/../../.symlinks/plugins/geolocator_apple/ios"
        config.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
        
        # Add additional settings for geolocator_apple
        config.build_settings['DEFINES_MODULE'] = 'YES'
        config.build_settings['SWIFT_INCLUDE_PATHS'] = "${PODS_ROOT}/../Flutter"
      end
      
      # Fix deprecation warnings for image_picker_ios
      if target.name == 'image_picker_ios'
        # Add build setting to use modern UTType API instead of deprecated kUTType constants
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= []
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'DISABLE_KTTYPE_USE=1'
        config.build_settings['OTHER_SWIFT_FLAGS'] = '$(inherited) -DDISABLE_KTTYPE_USE'
        
        # Add our custom Swift extension file to the image_picker_ios target
        config.build_settings['SWIFT_VERSION'] = '5.0'
        config.build_settings['CLANG_ENABLE_MODULES'] = 'YES'
        
        # Suppress specific deprecation warnings
        config.build_settings['GCC_WARN_ABOUT_DEPRECATED_FUNCTIONS'] = 'NO'
        config.build_settings['CLANG_WARN_DEPRECATED_OBJC_IMPLEMENTATIONS'] = 'NO'
      end
    end
  end
end
